# Generated by Django 5.0.2 on 2025-11-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_escolar_desit_api', '0003_alumnos_maestros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('seccion', models.CharField(blank=True, max_length=255, null=True)),
                ('dias_json', models.TextField(blank=True, null=True)),
                ('hora_inicio', models.CharField(blank=True, max_length=255, null=True)),
                ('hora_final', models.CharField(blank=True, max_length=255, null=True)),
                ('salon', models.CharField(blank=True, max_length=255, null=True)),
                ('programa_edu', models.CharField(blank=True, max_length=255, null=True)),
                ('profesor', models.CharField(blank=True, max_length=255, null=True)),
                ('creditos', models.CharField(blank=True, max_length=255, null=True)),
                ('creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
